services:
    hydrator:
        class: Lexide\Reposition\Clay\Hydrator\ClayHydrator
        arguments:
            - "@entityFactory"
        calls:
            -
                method: "setNormaliser"
                arguments:
                    - "@lexide_reposition.defaultNormaliser"

    metadataFactory:
        class: Lexide\Reposition\Clay\Metadata\ClayMetadataFactory

    entityFactory:
        class: Lexide\Reposition\Clay\Hydrator\EntityFactory
        arguments:
            - "@lexide_reposition.collectionFactory"

    lexide_reposition.defaultHydrator:
        aliasOf: "@hydrator"

    lexide_reposition.defaultMetadataFactory:
        aliasOf: "@metadataFactory"

    lexide_reposition.defaultEntityFactory:
        aliasOf: "@entityFactory"
